create view MEMBER_VIEW
AS
  SELECT
    APP.MEMBERS.NUMBER,
    APP.MEMBERS.IS_SUSPENDED,
    APP.MEMBER_INFO.NAME,
    APP.LOCATIONS.CITY,
    APP.LOCATIONS.STATE,
    APP.LOCATIONS.STREET_ADDRESS,
    APP.LOCATIONS.ZIPCODE
  FROM APP.MEMBERS
    JOIN APP.MEMBER_INFO USING (NUMBER)
    JOIN APP.ENTITY_LOOKUP ON APP.MEMBERS.NUMBER = APP.ENTITY_LOOKUP.MEMBER_NUMBER
    JOIN APP.LOCATIONS ON APP.ENTITY_LOOKUP.MEMBER_NUMBER = APP.MEMBERS.NUMBER