create view MEMBER_VIEW
AS
  SELECT
    MEMBERS.NUMBER,
    MEMBERS.IS_SUSPENDED,
    MEMBER_INFO.NAME,
    LOCATIONS.CITY,
    LOCATIONS.STATE,
    LOCATIONS.STREET_ADDRESS,
    LOCATIONS.ZIPCODE
  FROM MEMBERS
    JOIN MEMBER_INFO USING (NUMBER)
    JOIN ENTITY_LOOKUP ON MEMBERS.NUMBER = ENTITY_LOOKUP.MEMBER_NUMBER
    JOIN LOCATIONS ON ENTITY_LOOKUP.MEMBER_NUMBER = MEMBERS.NUMBER