create view PROVIDER_VIEW
AS
  SELECT
    PROVIDERS.NUMBER,
    PROVIDERS.NAME,
    LOCATIONS.CITY,
    LOCATIONS.STATE,
    LOCATIONS.STREET_ADDRESS,
    LOCATIONS.ZIPCODE
  FROM PROVIDERS
    JOIN ENTITY_LOOKUP ON PROVIDERS.NUMBER = ENTITY_LOOKUP.PROVIDER_NUMBER
    JOIN LOCATIONS ON ENTITY_LOOKUP.PROVIDER_NUMBER = PROVIDERS.NUMBER
