create view PROVIDER_VIEW
AS
  SELECT
    APP.PROVIDERS.NUMBER,
    APP.PROVIDERS.NAME,
    APP.LOCATIONS.CITY,
    APP.LOCATIONS.STATE,
    APP.LOCATIONS.STREET_ADDRESS,
    APP.LOCATIONS.ZIPCODE
  FROM APP.PROVIDERS
    JOIN APP.ENTITY_LOOKUP ON APP.PROVIDERS.NUMBER = APP.ENTITY_LOOKUP.PROVIDER_NUMBER
    JOIN APP.LOCATIONS ON APP.ENTITY_LOOKUP.PROVIDER_NUMBER = APP.PROVIDERS.NUMBER
